config/routes.rb
HTMLcast::Application.routes.draw do
  resources :comments

  scope :path => '/(:locale)', :constraints => { :locale => /#{I18n.available_locales.join('|')}/ } do
    resources :categories do
      resources :posts
    end

    devise_for :users
    resources :users do
      resources :posts
    end

    resources :posts do
      resources :comments
    end

    resources :pages do
      resources :comments
    end

    root :to => "posts#index"
    match ':controller/:action/:id(.:format)'
  end

end

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content, :class => 'mceEditor' %>
  </p>
  <p>
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </p>
  <p>
    <%= f.select :parent_id, @pages_tree %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/pages/_page.html.erb
<div class="navigation lvl<%= page.depth %>">
  <%= link_to(page.title, page, :class => current_page?(page) ? 'hi' : '') %>
  <span>_</span>
</div>

app/views/pages/edit.html.erb
<%= "Edit Page" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @page %> |
  <%= link_to "View All", pages_path %>
</p>

app/views/pages/index.html.erb
<%= "Pages" %>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Published At</th>
    <th>User</th>
    <th>Ancestry</th>
  </tr>
  <% for page in @pages %>
    <tr>
      <td><%= page.title %></td>
      <td><%= page.content %></td>
      <td><%= page.published_at %></td>
      <td><%= page.user_id %></td>
      <td><%= page.ancestry %></td>
      <td><%= link_to "Show", page %></td>
      <td><%= link_to "Edit", edit_page_path(page) %></td>
      <td><%= link_to "Destroy", page, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Page", new_page_path %></p>

app/views/pages/new.html.erb
<%= "New Page" %>

<%= render 'form' %>

<p><%= link_to "Back to List", pages_path %></p>

app/views/pages/show.html.erb
<%= content_tag :h1, @page.title %>
<div class="entry">
  <%= @page.content.html_safe %>
</div>

<% if can? :manage, @page -%>
  <%= content_tag :p do %>
    <%= link_to "Edit", edit_page_path(@page) %> |
    <%= link_to "Destroy", @page, :confirm => 'Are you sure?', :method => :delete %> |
    <%= link_to "View All", pages_path %>
  <% end -%>
<% end -%>

<%= content_tag :h2, t(:comments, :scope => :comments) %>
<%= nested_comments @comments %>
<%= render :partial => 'comments/form', :locals => { :comment => @page.comments.build } %>