config/routes.rb
HTMLcast::Application.routes.draw do
  resources :comments

  scope :path => '/(:locale)', :constraints => { :locale => /#{I18n.available_locales.join('|')}/ } do
    resources :categories do
      resources :posts
    end

    devise_for :users
    resources :users do
      resources :posts
    end

    resources :posts do
      resources :comments
    end

    resources :pages do
      resources :comments
    end

    root :to => "posts#index"
    match ':controller/:action/:id(.:format)'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  has_many :comments, :as => :commentable

  before_create :set_permalink

  acts_as_taggable

  def content
    super.html_safe
  end

  def to_param
    [id, permalink].join('-')
  end

  protected

  def set_permalink
    self.permalink = title.downcase.gsub(/[^0-9a-z]+/, ' ').strip.gsub(' ', '-') if title
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :load_posts, :only => :index
  before_filter :load_post,  :only => [:show, :edit, :update, :destroy]
  before_filter :set_category_tree, :only => [:new, :edit]

  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html
      format.atom
    end
  end

  def show
    @comments = @post.comments.arrange(:order => :created_at)
  end

  def new
    @post = current_user.posts.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end

  protected
    include Modules::CategorySelector

    def load_posts
      @posts = if params[:user_id].present?
        User.find(params[:user_id]).posts
      elsif params[:category_id].present?
        load_category.posts
      else
        Post
      end.order('created_at DESC').page(params[:page]).per(10)

      @posts = @posts.where('title LIKE ? OR content LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
      @posts = @posts.tagged_with(params[:tag]) if params[:tag].present?
    end

    def load_post
      @post = Post.find(params[:id])
    end

    def load_category
      @category ||= Category.find(params[:category_id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :class => 'mceEditor' %>
  </div>
  <div class="field">
    <%= f.select(:status_id, statuses_for_select(Post)) %>
  </div>
  <div class="field">
    <%= f.select :category_id, @categories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_video.html.erb
<div>
  <video controls="controls">
    <source	src="<%= @post.video %>.m4v" />
    <source src="<%= @post.video %>.ogv" />
  </video>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if @posts.blank? %>
  <%= content_tag :h1, t(:no_posts, :scope => :posts) %>
  <%= content_tag :p, t(:no_posts_txt, :scope => :posts) %>
<% end %>

<%= paginate @posts %>
<% @posts.each_with_index do |post, i| %>
  <%= content_tag :hr if i > 0 %>
  <%= content_tag(:h1, link_to(post.title, category_post_path(post.category, post))) %>
  <div class="sub_header">
    <%= t(:posted_by, :scope => :posts, 
      :name => link_to(post.user.name, user_posts_path(post.user)), 
      :in => link_to(post.category.title, category_posts_path(post.category)),
      :at => l(post.created_at, :format => :short)).html_safe %>
  </div>
  <div class="content">
    <%= post.content %>
  </div>
  <div class="comment_count">
    <%= link_to(t(:count, :scope => :comments, :count => post.comments.count), post_url(post, :anchor => 'comments')) %>
  </div>

  <%= link_to 'Edit', edit_post_path(post) if can? :edit, @post %>
  <%= link_to 'Destroy', posts_path, :confirm => 'Are you sure?', :method => :delete if can? :destroy, @post %>
<% end %>

<%= content_tag(:p, link_to('New Post', new_post_path)) if can? :edit, @post %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= content_tag :h1, @post.title %>

<%= @post.content.html_safe %>

<%= render :partial => 'video', :locals => { :post => @post } if @post.video.present? %>

<% if can? :manage, @post -%>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
<% end -%>

<a name="comments"></a>
<%= content_tag :h2, t(:comments, :scope => :comments) %>
<%= nested_comments @comments %>
<%= render :partial => 'comments/form', :locals => { :comment => @post.comments.build } %>