config/routes.rb
HTMLcast::Application.routes.draw do
  resources :comments

  scope :path => '/(:locale)', :constraints => { :locale => /#{I18n.available_locales.join('|')}/ } do
    resources :categories do
      resources :posts
    end

    devise_for :users
    resources :users do
      resources :posts
    end

    resources :posts do
      resources :comments
    end

    resources :pages do
      resources :comments
    end

    root :to => "posts#index"
    match ':controller/:action/:id(.:format)'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  has_ancestry

  def to_param
    [id, title.downcase.gsub(/[^0-9a-z]+/, ' ').strip.gsub(' ', '-')].join("-")
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :load_categories, :only => :index
  before_filter :load_category,  :only => [:show, :edit, :update, :destroy]
  before_filter :set_category_tree, :only => [:new, :edit]
  before_filter :admin?, :except => [:show]

  def index
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end

  protected
    include Modules::CategorySelector

    def load_categories
      @categories = Category.all
    end

    def load_category
      @category = Category.find(params[:id])
    end

    def admin?
      redirect_to root_url unless authenticate_user! && current_user.admin?
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def build_categories(categories)
    categories.map do |category, sub_categories|
      render(:partial => 'categories/list', :locals => { :category => category }) + content_tag(:div, build_categories(sub_categories), :class => "nested_categories")
    end.join.html_safe
  end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.select(:status_id, statuses_for_select(Post)) %>
  </div>
  <div class="field">
    <%= f.select :parent_id, @categories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_list.html.erb
<div class="navigation lvl<%= category.depth %>">
  <%= link_to(category.title, category_posts_path(category)) %>
  <!-- , :class => current_page?(page) ? 'hi' : '' -->
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.title %></td>
    <td><%= status_for(category) %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>

<p>
  <b>Status:</b>
  <%= status_for(@category) %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>