config/routes.rb
HTMLcast::Application.routes.draw do
  resources :comments

  scope :path => '/(:locale)', :constraints => { :locale => /#{I18n.available_locales.join('|')}/ } do
    resources :categories do
      resources :posts
    end

    devise_for :users
    resources :users do
      resources :posts
    end

    resources :posts do
      resources :comments
    end

    resources :pages do
      resources :comments
    end

    root :to => "posts#index"
    match ':controller/:action/:id(.:format)'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_locale, :set_tags
  before_filter :set_pages
  before_filter :set_categories

  protect_from_forgery

  def set_locale
    I18n.locale = params[:locale]
  end

  def default_locale?
    I18n.locale == I18n.default_locale
  end

  def default_url_options
    { :locale => default_locale? ? nil : I18n.locale }
  end

  def set_tags
    @tags = Post.tag_counts_on(:tags)
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url
  end

  def set_pages
    @pages = Page.arrange
  end

  def set_categories
    @main_categories = Category.arrange
  end
end

app/helpers/application_helper.rb
require 'uri'
module ApplicationHelper
  def avatar_url(email)
    #default_url = "#{root_url}images/guest.png" ##{CGI.escape(default_url)}
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48&d=mm"
  end
end

app/views/application/_navigation.html.erb
<nav class="nav">
  <div class="navigation lvl0">
    <%= link_to 'Home'.html_safe, root_url %>
    <span>_</span>
  </div>
  <%= build_navigation @pages if @pages.present? %>
  <%= link_to '&copy; 2011 HTMLCASTS'.html_safe, root_url %>
</nav>

app/views/application/_search_form.html.erb
<%= form_tag posts_path, :method => 'get' do %>
  <p>
    <strong>Suchbegriff eingeben</strong>
    <%= search_field_tag :search, params[:search], :results => 5, :placeholder => t(:search, :scope => :posts), :autosave => "html_cast_search" %>
    <%= image_submit_tag '/assets/layout/search_button.png', :name => nil %>
  </p>
<% end -%>

app/views/application/_tag_cloud.html.erb
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, posts_url(:tag => tag.name), :class => css_class %>
<% end %>